### ISSUE TITLE
现在还有效嘛

### ISSUE THREAD

**Issue by barkure** [SuInk/csu-auto-sign#1]
学校的打卡页面好像有小改，现在还有效嘛

**Comment by SuInk** [comment]
学院通知不让我们用程序打卡，我现在都是手动打的卡。。不过学校的打卡网站原理没多大变化，应该还能用。或者你可以使用其他作者的打卡程序

**Comment by barkure** [comment]
Ok🥳



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月10日(周一) 中午1:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SuInk/csu-auto-sign] 现在还有效嘛 (Issue #1)




 
学院通知不让我们用程序打卡，我现在都是手动打的卡。。不过学校的打卡网站原理没多大变化，应该还能用。或者你可以使用其他作者的打卡程序
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
